default DEVICE_CREDENTIAL to /etc/device-credentials
fedora-iot/fido-device-onboard-rs pull request #204
Opened 2022-02-09 11:08 UTC by mangelajo

This will match fdo-linuxclient-app to the fdo-manufacturing-client
behavior.

Fixes-Issue: #203

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2022-02-11 08:03 UTC, puiterwijk commented
That's not the way we prefer to add additional paths.
This is the `FileSystemPathEnv` location provider, which should only be for reading environment variables.
In order to also look at `/etc/device-credentials`, you'd add a `FileSystemPath` instance at [`pub fn find()`](https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/util/src/device_credential_locations.rs#L10)

2022-02-11 08:05 UTC, puiterwijk requested changes
The intention is that the `find()` method has a list of places where to search for device credentials, and that each possible place is either "yes, it's there", or "no, not there".
So having the environment variable say "yes, it's there", all the time, is not ideal.

2022-02-11 10:38 UTC, mangelajo commented
hey thanks @puiterwijk yes, that's what I understood from the code.

What I found missing then was the ability to define a deactivation method:

https://github.com/fedora-iot/fido-device-onboard-rs/pull/204/files#diff-a6defb265b6577f2e084ab6d98f948240cc7734140f8516ea63b091a3ba9cba0R11

In my first version of the patch I used what you suggested, but I found the ability to specify deactivation lacking.

What's your opinion on this if I switch back to that form?, should we capture the deactivation method from environment in that case? (I understand that the qemu provided is not mutable, but a filesystem one would be...).

I followed this path because it's the last priority element, and did want to provide flexibility on deactivation, but let's decide how to handle that detail and I can update the PR.

2022-02-16 14:12 UTC, puiterwijk commented
How about adding this to `fn find()`:
```
        Box::new(FileSystemPath {
            path: "/etc/device-credentials".to_string(),
            deactivation_method: DeactivationMethod::Deactivate,
        }),
```

2022-02-16 16:28 UTC, mangelajo commented
Yes, that was my first version, but then there is no control on deactivation. Is it mandatory to always deactivate? what if we want to support ownership transfer later?

2022-02-16 16:29 UTC, mangelajo commented
It's fine for me, I can update the patch to that :) only wanted to share my line of thought, and why I ended doing it via environment.

2022-02-22 13:07 UTC, puiterwijk approved these changes

2022-02-22 13:08 UTC, puiterwijk commented
Thanks for the patch!
Your commit message will need a "type" prefix, possibly `feature: `?

2022-03-08 09:25 UTC, mangelajo commented
Sorry for the slow update, I haver rebased on main, and updated the commit message.

2022-03-18 08:22 UTC, runcom commented
lgtm

2022-03-24 10:30 UTC, puiterwijk commented
@Mergifyio rebase

2022-03-24 10:30 UTC, puiterwijk submitted a review, later dismissed

2022-10-24 09:14 UTC, 7flying commented
@mangelajo ci complains about the commit message, can you amend "feature:" to "feat:"?

2022-10-24 09:21 UTC, mangelajo commented
> @mangelajo ci complains about the commit message, can you amend "feature:" to "feat:"?

sure thing, 1 sec

2022-10-24 09:27 UTC, mangelajo commented
@7flying, the commit should be good now 🤞; thanks for the ping! 👍

2022-10-24 09:29 UTC, 7flying approved these changes
LGTM
Thanks for your contribution!

2022-10-24 09:49 UTC, merged